### ISSUE TITLE
AttributeError: 'TAF' object has no attribute '_TAF__raw_taf'

### ISSUE THREAD

**Issue by dscarlat** [dmbaturin/pytaf#10]
call to .get_taf() returns error:
AttributeError: 'TAF' object has no attribute '_TAF__raw_taf'

Probably line 420 has one extra underscore "_"

https://github.com/dmbaturin/pytaf/blob/1bbd702567545bbe7369a76a519024bff4368f3a/lib/pytaf/taf.py#L420

**Comment by dmbaturin** [comment]
Good find! Looks like I was going to make it private but then changes my mind and made it protected but forgot to change it everywhere.

I've made a new pypi release too.
